apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: dependency-import-tracker-designsystem
  namespace: designsystem
  labels:
    team: designsystem
spec:
  image: {{ image }}
  port: 3000
  ingresses:
    - "https://dependency-tracker.dev.nav.no"
  liveness:
    path: /api/isAlive
  readiness:
    path: /api/isAlive
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
  gcp:
    buckets:
      - name: dependency-tracker-designsystem