name: CI-VERSION

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test-versioning:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
          token: ${{secrets.GITHUB_TOKEN}}
      - uses: actions/setup-node@v1
        with:
          registry-url: http://registry.npmjs.org
          node-version: 14
      - name: Node-modules cache
        uses: actions/cache@v2
        id: node-cache
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: install
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: yarn install

      - name: comment on PR
        if: always()
        uses: ./.github/workflows/comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
